version: '2'
services:
  accountancy-app:
    image: accountancy
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accountancy-postgresql:5432/accountancy
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  accountancy-postgresql:
    extends:
      file: postgresql.yml
      service: accountancy-postgresql
